Return 1 on failure

diff --git a/bin/abspath b/bin/abspath
--- a/bin/abspath
+++ b/bin/abspath
@@ -1,4 +1,8 @@
 #!/bin/sh
 # Print the absolute path to a given file or directory
 # usage: abspath <file>
+# exit code: 0 success
+#           >0 failure
+
+[ ! -f "$1" ] && exit 1
 echo "$(cd "$(dirname "$1")"; pwd)/"$(basename "$1")""
